# Generated by Django 4.2.2 on 2023-07-03 04:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_created_user_friends_user_updated_friendrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="friendrequest",
            name="accepted",
            field=models.BooleanField(null=True, verbose_name="accepted"),
        ),
    ]
