# Generated by Django 4.2.2 on 2023-07-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_friendrequest_from_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=200, verbose_name="last name"),
        ),
    ]
