[project]
name = "accuknox-assignment"
version = "0.1"
requires-python = ">=3.10"
dependencies = ["django", "djangorestframework", "django-filter"]

[tool.setuptools]
py-modules = []

[project.optional-dependencies]
dev = ["black", "ruff"]
